# output dir will be created by hydra
data_dir: /eos/home-k/kiwoznia/data/rodem/nuflows/stop
output_dir: ${oc.env:PROJECT_ROOT}

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
